### ISSUE TITLE
Binary issue on mac os

### ISSUE THREAD

**Issue by Eth3rnit3** [MiddleSchoolStudent/BotBrowser#1]
Hi and congratulations on your work and this initiative.

I hadn't thought about it but I have to admit that it's probably the best approach to take. The task still seems very long and difficult but you've made me want to take a closer look at chromium. I'm currently compiling my first local version.

While waiting to know where to start myself, I wanted to try out the mac os version you're proposing. I think I followed your explanations correctly, but my Mac doesn't seem to want to run the binary.

I'm on M4 so maybe that's why I don't know.

Here's the command I execute

```sh
/Applications/Chromium.app/Contents/MacOS/Chromium --user-data-dir=$HOME/.config/google-chrome/Default --bot-profile=$HOME/Downloads/chrome130-macarm.enc --no-sandbox --disable-blink-features=AutomationControlled --disable-audio-output --exclude-switches=disable-crash-reporter,disable-crashpad-for-testing,disable-gpu-watchdog
```

I've also tried without the user-data-dir or exclude-switches but I get the same error every time
<img width="998" alt="Capture d’écran 2024-11-19 à 22 58 37" src="https://github.com/user-attachments/assets/7b62f3c2-6af9-4cd3-ad5f-9f6235405fc1">

```sh
System Version: macOS 15.1 (24B2083)
Kernel Version: Darwin 24.1.0
Model Name: MacBook Pro
Model Identifier: Mac16,1
Chip: Apple M4
Memory: 16 GB
```

**Comment by MiddleSchoolStudent** [comment]
> Hi and congratulations on your work and this initiative.
> 
> I hadn't thought about it but I have to admit that it's probably the best approach to take. The task still seems very long and difficult but you've made me want to take a closer look at chromium. I'm currently compiling my first local version.
> 
> While waiting to know where to start myself, I wanted to try out the mac os version you're proposing. I think I followed your explanations correctly, but my Mac doesn't seem to want to run the binary.
> 
> I'm on M4 so maybe that's why I don't know.
> 
> Here's the command I execute
> 
> ```shell
> /Applications/Chromium.app/Contents/MacOS/Chromium --user-data-dir=$HOME/.config/google-chrome/Default --bot-profile=$HOME/Downloads/chrome130-macarm.enc --no-sandbox --disable-blink-features=AutomationControlled --disable-audio-output --exclude-switches=disable-crash-reporter,disable-crashpad-for-testing,disable-gpu-watchdog
> ```
> 
> I've also tried without the user-data-dir or exclude-switches but I get the same error every time <img alt="Capture d’écran 2024-11-19 à 22 58 37" width="998" src="https://private-user-images.githubusercontent.com/27304829/387854368-7b62f3c2-6af9-4cd3-ad5f-9f6235405fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjUxNTYsIm5iZiI6MTczMjA2NDg1NiwicGF0aCI6Ii8yNzMwNDgyOS8zODc4NTQzNjgtN2I2MmYzYzItNmFmOS00Y2QzLWFkNWYtOWY2MjM1NDA1ZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAxMDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OTdmNWJiOGI2NWZmZWMwOWM4MTJlYTAzM2NiNzkzMzc3NjAwYTAyZDY2NzcxOGIxZmJhMTk2NzA5N2I4MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LAer6D9YepIyHxclxAOlbBDhvm-ij1_Qj9BfGGjtpR4">
> 
> ```shell
> System Version: macOS 15.1 (24B2083)
> Kernel Version: Darwin 24.1.0
> Model Name: MacBook Pro
> Model Identifier: Mac16,1
> Chip: Apple M4
> Memory: 16 GB
> ```


I'm assuming you may need to sign it, please try:
```sh
codesign --force --deep --sign - Chromium.app
```

**Comment by Eth3rnit3** [comment]
No, it doesn't seem to be having the desired effect.

```sh
➜  /Applications codesign --force --deep --sign - Chromium.app
Chromium.app: replacing existing signature
Chromium.app: resource fork, Finder information, or similar detritus not allowed
```

Same error message after trying to open Chromium

**Comment by MiddleSchoolStudent** [comment]
> No, it doesn't seem to be having the desired effect.
> 
> ```shell
> codesign --force --deep --sign - Chromium.app
> Chromium.app: replacing existing signature
> Chromium.app: resource fork, Finder information, or similar detritus not allowed
> ```
> 
> Same error message after trying to open Chromium

In the system settings `Privacy & Security`, allow `Chromium.app` to execute under `Allow applications downloaded from`.

**Comment by Eth3rnit3** [comment]
No sorry, same problem

**Comment by MiddleSchoolStudent** [comment]
> No sorry, same problem

Please try to remove quarantine attribute via:
```
xattr -rd com.apple.quarantine Chromium.app
```

or disable Gatekeeper:

```
sudo spctl --master-disable
```

**Comment by Eth3rnit3** [comment]
```sh
xattr -rd com.apple.quarantine Chromium.app
```
<img width="1200" alt="screenshot" src="https://github.com/user-attachments/assets/2b3e7f71-14e9-4fee-9d0b-33fc1ba4b316">

This was just the command I needed, thank you so much for your help 💪
