### ISSUE TITLE
Stealth issue

### ISSUE THREAD

**Issue by Eth3rnit3** [MiddleSchoolStudent/BotBrowser#2]
I've just carried out a few tests with my [chromate](https://github.com/Eth3rnit3/chromate) project and unless I'm using something incorrectly, but I've made sure to provide only the arguments that are present in the demo. I lose efficiency against an unpatched version of chrome running in a docker container with xfvb. 

```log
[Chromate] 2024-11-20 21:08:45 DEBUG: Starting browser with args: ["/Applications/Chromium.app/Contents/MacOS/Chromium", "--user-data-dir=/Users/eth3rnit3/.config/google-chrome/Default", "--bot-profile=$HOME/Downloads/chrome130-macarm.enc", "--disable-audio-output", "--no-sandbox", "--disable-blink-features=AutomationControlled", "--headless=new", "--remote-debugging-port=50177"]
```

The only gain is on pixelscan where the ip is not interfered with, but this seems to add a problem at the webGL vendor level, cloudflare detects abnormal activity and the use of the mouse via CDP is detected.

You can see the differences with docker + xfvb here https://github.com/Eth3rnit3/chromate/pull/15/files

**Comment by Eth3rnit3** [comment]
Thanks for your feedback and explanations, it's very clear. I can confirm that the problem was mine. I was using the `$HOME` variable for the path to the profile and it was being misinterpreted when passing arguments. I had started to install a [patcher](https://github.com/Eth3rnit3/chromate/blob/main/lib/chromate/actions/stealth.rb) to try to correct the fingerprint, but in the end, it was causing me harm with the use of BotBrowser. Once these two problems were removed, everything worked exactly as you said.

https://github.com/Eth3rnit3/chromate/pull/15/commits/1e59c4badcb655b1b35f07d53939fba36198ef2f

Thank you very much for your help and your work.

**Comment by Eth3rnit3** [comment]
For your information, I've just redone the test with the first profile (the one provided in the repo) and the only change is that the fingerprint becomes inconsistent on pixelscan.

I have one last question. On Mac OS, is the whole Chromium.app folder necessary? Or if an installation already exists, can I simply replace the binary?

**Comment by MiddleSchoolStudent** [comment]
> For your information, I've just redone the test with the first profile (the one provided in the repo) and the only change is that the fingerprint becomes inconsistent on pixelscan.
> 
> I have one last question. On Mac OS, is the whole Chromium.app folder necessary? Or if an installation already exists, can I simply replace the binary?

Need to replace the full .app.
